# ==========================
# Database Configuration
# ==========================
spring.datasource.url=jdbc:mysql://hayabusa.proxy.rlwy.net:10534/railway?useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=IygRpBnlJQRnujZJUGIjekDHGdGPEdiz
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================
# JPA / Hibernate
# ==========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ==========================
# JWT Configuration
# ==========================
metromind.jwt.secret=${JWT_SECRET}
metromind.jwt.expiration-ms=86400000

# ==========================
# Server Configuration
# ==========================
server.port=${PORT:8080}
server.error.include-message=always
